language : node_js
node_js :
 - stable
python:
 - 2.7
before_install:
  - pip install --upgrade pip
install:
 - git clone https://github.com/ifrunistuttgart/pymavlink 
 - pip install -r ./pymavlink/requirements.txt
 - pip install flake8 pytest pytest-mock  
 - git clone https://github.com/mavlink/mavlink
 - python pymavlink/tools/mavgen.py --lang TypeScript --wire-protocol 2.0 -o ./assets ./mavlink/message_definitions/v1.0/common.xml
 - npm install
script:
 - npm test
